server:
  port: 8081

spring:
  application:
    name: furnitures

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
  datasource:
    url: jdbc:postgresql://localhost:5432/furnitures
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver