server:
  port: 8080

spring:
  application:
    name: furnitureWithComponentsRepository
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: furnituresWithComponents
      port: 27017
      host: localhost